# Generated by Django 4.2.1 on 2023-05-21 19:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(choices=[('hh_api', 'Hh Api')], max_length=128)),
                ('area_id', models.BigIntegerField(db_index=True)),
                ('area_country_name', models.CharField(max_length=256)),
                ('area_city_name', models.CharField(max_length=256)),
                ('speciality', models.CharField(choices=[('development/backend', 'Backend'), ('development/frontend', 'Frontend'), ('development/machine_learning', 'Machine Learning')], max_length=256)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('salary_currency', models.CharField(choices=[('RUB', 'Rub'), ('USD', 'Usd')], max_length=64)),
                ('salary_from', models.BigIntegerField()),
                ('salary_to', models.BigIntegerField()),
            ],
        ),
    ]
