# Generated by Django 4.2.1 on 2023-05-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancy',
            new_name='VacancyStats',
        ),
    ]
