# Generated by Django 4.2.1 on 2023-05-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_rename_vacancy_vacancystats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancystats',
            name='salary_from',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancystats',
            name='salary_to',
            field=models.BigIntegerField(null=True),
        ),
    ]
