version: '3'

services:

  datacamp:
    platform: linux/x86_64
    image: cr.yandex/crparlvq5pji2gn67f8s/bebest_datacamp:latest
    build: datacamp
    container_name: datacamp
    env_file:
      - .env.prod
    depends_on:
      - db

  backend:
    platform: linux/x86_64
    image: cr.yandex/crparlvq5pji2gn67f8s/bebest_backend:latest
    build: backend
    container_name: backend
    command: ["--bind", "0.0.0.0:8000"]
    volumes:
      - static_volume:/static
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always

  db:
    platform: linux/x86_64
    image: postgres:15.2
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    env_file:
      - .env.prod
    restart: always

  nginx:
    platform: linux/x86_64
    image: cr.yandex/crparlvq5pji2gn67f8s/bebest_nginx:latest
    build: nginx
    container_name: nginx
    volumes:
      - static_volume:/static
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /var/www/certbot:/var/www/certbot:rw
      - /etc/letsencrypt/:/etc/letsencrypt/:rw


volumes:
  postgres_data:
  static_volume:
