version: '3'

services:

  datacamp:
    build: datacamp
    container_name: datacamp
    env_file:
      - .env
    depends_on:
      - db

  backend:
    build: backend
    container_name: backend
    command: ["--bind", "0.0.0.0:8000"]
    volumes:
      - static_volume:/static
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15.2
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    env_file:
      - .env

  nginx:
    build: nginx
    container_name: nginx
    volumes:
      - static_volume:/static
    ports:
      - 80:80
    depends_on:
      - backend


volumes:
  postgres_data:
  static_volume:
