#!/usr/bin/env python3
import os
import django
import sys
from pathlib import Path


sys.path.append(str(Path(__file__).parent.parent / 'bebest'))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'bebest.settings')
django.setup()


from export.views import _export_vacancy_stats
result = _export_vacancy_stats()
print(result)
