#!/usr/bin/env bash

set -e

sudo docker-compose -f /home/dbrusenin/bebest/docker-compose.yaml run --rm  certbot renew --force-renewal
sudo docker-compose -f /home/dbrusenin/bebest/docker-compose.yaml restart nginx backend
