# Generated by Django 4.2.1 on 2023-05-08 11:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatacampPost',
            fields=[
                ('insert_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('resource_name', models.CharField(max_length=128)),
                ('source_name', models.CharField(max_length=128)),
                ('canonized_url', models.CharField(max_length=2048, primary_key=True, serialize=False)),
                ('original_url', models.CharField(max_length=2048)),
                ('title', models.CharField(max_length=256)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('rank', models.BigIntegerField()),
                ('starting_text', models.TextField()),
                ('publish_timestamp', models.BigIntegerField()),
                ('author_username', models.CharField(blank=True, max_length=128, null=True)),
                ('views', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datacamp_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table_name', models.CharField(max_length=256)),
                ('destination_table_name', models.CharField(max_length=256)),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
    ]
