# Generated by Django 4.2.1 on 2023-05-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='canonized_url',
            field=models.CharField(db_index=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='post',
            name='source_name',
            field=models.CharField(choices=[('habr', 'Habr')], max_length=128),
        ),
    ]
