# Generated by Django 4.2.1 on 2023-05-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source_name',
            field=models.CharField(choices=[('habr', 'Habr'), ('medium', 'Medium'), ('distributed_computing_musings', 'Dcm')], max_length=128),
        ),
    ]
